errors:
  common:
    app_key:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-not-premium'
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-found'
    token:
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-found'
  test_errors:
    test_field:
      test_error: 'anything'
  check_presence:
    field:
      required: 'url_field_required'
    other_field:
      required: 'url_other_field_required'
  check_either_presence:
    any_id:
      required: 'any_id_required'